---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - heartbeat

- name: install heartbeat packages
  package:
    name: "{{ heartbeat_packages }}"
    state: "{{ heartbeat_package_state }}"
  notify: install heartbeat template

- name: configure heartbeat
  copy:
    content: |
      # Ansible managed

      {{ heartbeat_conf | to_nice_yaml(indent=2) }}
    dest: "{{ heartbeat_conf_path }}"
  notify: restart heartbeat
  when:
    - heartbeat_conf is defined
    - heartbeat_conf_manage | bool

- name: manage heartbeat services
  service:
    name: "{{ heartbeat_service_name }}"
    state: "{{ heartbeat_service_status }}"
    enabled: "{{ heartbeat_service_enabled }}"
