---
- name: restart heartbeat
  service:
    name: "{{ heartbeat_service_name }}"
    state: restarted

- name: install heartbeat template
  command: |
    heartbeat setup --template -E 'output.elasticsearch.enabled=true'
  when:
    - "heartbeat_conf is defined"
    - "'heartbeat' in heartbeat_conf"
    - "'output' in heartbeat_conf.heartbeat"
    - "'elasticsearch' in heartbeat_conf.heartbeat.output"
  ignore_errors: yes
