---
- name: Converge
  pre_tasks:
    - name: update apt package cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
  hosts: all
  roles:
    - role: nephelaiio.heartbeat
